-- NUCLEAR OPTION: Recreate signal_ledger table from scratch
-- Use this if 'Unknown Column' errors persist despite reloading schema cache.

-- 1. DROP EXISTING TABLE (Warning: Deletes all data)
DROP TABLE IF EXISTS signal_ledger CASCADE;

-- 2. CREATE TABLE WITH FULL SCHEMA
CREATE TABLE signal_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Core Signal Data
    signal_id TEXT UNIQUE NOT NULL,
    symbol TEXT NOT NULL,
    option_type TEXT NOT NULL, -- Mapped from 'action' in code
    entry_price FLOAT,
    stop_loss FLOAT,
    target_1 FLOAT,
    target_2 FLOAT,
    
    -- Brain Scores
    confluence FLOAT,
    xgb_score FLOAT,
    rl_score FLOAT,
    smc_score FLOAT,
    
    -- Market Context
    regime TEXT,
    vix FLOAT,
    volatility FLOAT,
    volume FLOAT,
    
    -- Complex Data
    sr_data JSONB,
    
    -- Metadata & State
    state TEXT DEFAULT 'PENDING', -- PENDING, ACTIVE, CLOSED, OUTCOME
    generated_at TIMESTAMPTZ,
    brain_version TEXT,
    
    -- Outcome & PnL Tracking (Updated by OutcomeTracker/API)
    pnl FLOAT,
    outcome TEXT, -- WIN, LOSS, BE
    closed_at TIMESTAMPTZ,
    exit_price FLOAT,
    exit_reason TEXT
);

-- 3. ENABLE RLS (Optional, standard credential overrides usually bypass this, but good practice)
ALTER TABLE signal_ledger ENABLE ROW LEVEL SECURITY;

-- 4. CREATE POLICY (Allow all access for service role/authenticated users)
CREATE POLICY "Enable all access" ON signal_ledger FOR ALL USING (true) WITH CHECK (true);

-- 5. RELOAD SCHEMA CACHE (Just in case)
NOTIFY pgrst, 'reload schema';
